version: '3.4'

services:
    open-telemetry-aspire:
        image: ${DOCKER_REGISTRY-}open-telemetry-aspire
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire.dashboard:18889
        networks:
            - otel
    
    aspire.dashboard:
        image: mcr.microsoft.com/dotnet/nightly/aspire-dashboard:latest
        container_name: dashboard
        ports:
            - "18888:18888"
        networks:
            - otel

networks:
    otel: